Buyer/urls.py
from django.urls import path,re_path
from Buyer.views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
path('indexx/',indexx),
path('loginn/',loginn),
path('registerr/',registerr),
path('logout/',logout),
# path('goods_list/',goods_list),
# path('goods_list/',cache_page(60*15)(goods_list)),   #设置缓存
path('goods_list/',goods_list),
path('user_center_info/',user_center_info),
path('place_order/',place_order),
path('cart/',cart),
path('user_center_order/',user_center_order),
path('user_center_site/',user_center_site),
path('AlipayViews/',AlipayViews),
path('payresult/',payresult),
path('add_cart/',add_cart),
path('place_order_more/',place_order_more),
path('reqtest/',reqtest),
path('myprocess_tem_rep/',myprocess_tem_rep),
re_path('detail/(?P<id>\d+)',detail),

]

Qshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from Buyer.views import indexx

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Saller/",include("Saller.urls")),
    path("Buyer/",include("Buyer.urls")),
    re_path('^$',indexx)
]

Buyer/models.py
from django.db import models
from Saller.models import *
# Create your models here.
class LoginUserr(models.Model):
    ## id 不需要写
    email = models.EmailField()
    password = models.CharField(max_length=32)
    username = models.CharField(max_length=32,null=True,blank=True)
    phone_number = models.CharField(max_length=11,null=True,blank=True)
    photo = models.ImageField(upload_to="images",null=True,blank=True)   ## /static/images
    age = models.IntegerField(null=True,blank=True)
    gender = models.CharField(null=True,blank=True,max_length=4)
    address = models.TextField(null=True,blank=True)


ORDER_STATUS=(
    (0,'未支付'),
    (1,'已支付'),
    (2,'待发货'),
    (3,'待收货'),
    (4,'完成'),
    (5,'拒收'),
)

## 订单表
class PayOrder(models.Model):
    ###订单状态：
    # 0 未支付
    # 1 已支付
    # 2  待发货
    # 3  待收货
    # 4   完成
    # 5   拒收
    order_number = models.CharField(max_length=32,verbose_name="订单编号",unique=True)
    order_date = models.DateField(auto_now=True,verbose_name="订单日期")
    # order_status = models.IntegerField(verbose_name="订单状态")
    order_status=models.IntegerField(choices=ORDER_STATUS,verbose_name='订单状态')
    order_total = models.FloatField(verbose_name="订单总价 ")
    order_user = models.ForeignKey(to= LoginUserr,on_delete=models.CASCADE,verbose_name="订单用户")## 外键  链接到  用户表


ORDERINFO_STATUS=(
    (0,'未支付'),
    (1,'已支付'),
    (2,'已发货'),
    (3,'已完成'),
    (4,'拒绝订单'),
)
## 订单详情表
class OrderInfo(models.Model):
    order_id = models.ForeignKey(to=PayOrder,on_delete=models.CASCADE,verbose_name="订单表外键")
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE,verbose_name="商品表")
    goods_price = models.FloatField(verbose_name='商品单价')
    goods_count = models.IntegerField(verbose_name="商品数量")
    goods_total_price = models.FloatField(verbose_name="商品小计")
    store_id = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="店铺id")
    status = models.IntegerField(choices=ORDERINFO_STATUS,verbose_name='订单详情状态',default=0)

class Cart(models.Model):
    goods_number=models.IntegerField(verbose_name='商品数量')
    goods_price=models.FloatField(verbose_name='商品价格')
    goods_total=models.FloatField(verbose_name='商品总价')
    goods=models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    user=models.ForeignKey(to=LoginUserr,on_delete=models.CASCADE)
    order_number=models.CharField(max_length=32,default=0)


class UserAddress(models.Model):
    user_name=models.CharField(max_length=10)
    user_address=models.CharField(max_length=50)
    user_post=models.CharField(max_length=32)
    user_phone=models.CharField(max_length=22)
    status=models.IntegerField(default=0)
    user=models.ForeignKey(to=LoginUserr,on_delete=models.CASCADE)

Buyer/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse

from Saller.models import *
from Buyer.models import *

import hashlib
from django.core.paginator import Paginator
import time
from alipay import AliPay
from Qshop.settings import alipay_public_key_string,alipay_private_key_string
# Create your views here.
from django.views.decorators.cache import cache_page
import logging

collect=logging.getLogger('django')
## 密码加密
def setPassword(password):
    md5 = hashlib.md5()
    md5.update(password.encode())
    result = md5.hexdigest()
    return result
def LoginVaild(func):
    ## 1. 获取cookie中username和email
    ## 2. 判断username和email
    ## 3. 如果成功  跳转
    ## 4. 如果失败   login.html
    def inner(request,*args,**kwargs):
        email = request.COOKIES.get('email')
        ## 获取session
        session_email = request.session.get("email")
        # print(email)
        if email and session_email and email == session_email:
            user_email=LoginUserr.objects.filter(email=email).exists()
            # print(user_email)
            if user_email:
                return func(request,*args,**kwargs)
            else:
                return HttpResponseRedirect('/Buyer/loginn/')
        else:
            return HttpResponseRedirect('/Buyer/loginn/')
    return inner
# @cache_page(60*20)
@LoginVaild
def indexx(request):
    # print('im view')
    # 1/0
    goods_type=GoodsType.objects.all()
    result=[]
    for type in goods_type:
        goods=type.goods_set.order_by('-goods_price')
        if len(goods)>4:
            goods=goods[:4]
            result.append({'type':type,'goods':goods})
            collect.warning('---------%s is login----')
    return render(request,'buyer/index.html',locals())
def loginn(request):
    if request.method == "POST":
        error_msg = ""
        email = request.POST.get("email")
        password = request.POST.get("password")
        if email:
            user = LoginUserr.objects.filter(email=email).first()
            # print(user.email)
            if user:
                ## 存在
                if user.password == setPassword(password):
                    ## 登录成功
                    ## 跳转页面
                    # error_msg = "登录成功"
                    # return HttpResponseRedirect('/index/')
                    ## 设置cookie
                    response  = HttpResponseRedirect("/Buyer/indexx/")
                    response.set_cookie("email",user.email)
                    response.set_cookie("userid",user.id)
                    request.session['email'] = user.email  ## 设置session
                    # collect.info('---------%s is login----'%user.email)
                    collect.warning('---------%s is login----'%user.email)
                    return response
                else:
                    error_msg = "密码错误"
            else:
                error_msg = "用户不存在"
        else:
            error_msg = "邮箱不可以为空"
    return render(request,'buyer/login.html',locals())
def registerr(request):
    if request.method=='POST':
        error=''
        email=request.POST.get('email')
        password=request.POST.get('password')
        password2=request.POST.get('password2')
        if email and password and password2:
            loginuserr=LoginUserr.objects.filter(email=email).first()
            if not loginuserr:
                if password==password2:
                    user=LoginUserr()
                    user.email=email
                    # user.username=email
                    user.password=setPassword(password)
                    user.save()
                    error='注册成功'
                else:
                    error='两次密码不一致'
            else:
                error='邮箱已存在，请登录'
        else:
            error='用户名或密码不能为空'
    return render(request,'buyer/register.html',locals())
## 登出
def logout(request):
    # 删除cookie   删除  session
    response = HttpResponseRedirect("/Buyer/loginn/")
    # response.delete_cookie("kename")
    keys = request.COOKIES.keys()
    for one in keys:
        response.delete_cookie(one)

    request.session.flush()
    return response


def goods_list(request):
    # goods=Goods.objects.all()
    # recommend=Goods.objects.order_by("-goods_pro_time")
    # """
    # 根据 keywords传递的类型id，寻找该类型下面的商品
    # """
    keywords = request.GET.get("keywords")
    req_type=request.GET.get('req_type')
    if req_type=='findall':
        goods_type = GoodsType.objects.get(id=keywords)
        goods = goods_type.goods_set.all()   ## 反向查询，
    elif req_type=='search':
        goods=Goods.objects.filter(goods_name__contains=keywords).all()
    end = len(goods) // 5
    end += 1
    recommend = goods.order_by("-goods_pro_time")[:end]
    return render(request,"buyer/goods_list.html",locals())

#详情
def detail(request,id):
    goods=Goods.objects.get(id=int(id))
    return render(request,'buyer/detail.html',locals())
#用户中心
def user_center_info(request):
    return render(request,'buyer/user_center_info.html',locals())


#购物车
def cart(request):
    user_id=request.COOKIES.get('userid')
    cart_list=[]
    cart=Cart.objects.filter(user_id=user_id).order_by('-id')
    count = cart.count()  # 获取条数
    for i in cart:
        if i.order_number!='0':
            try:
                payorder=PayOrder.objects.get(order_number=i.order_number)
                if payorder:
                    if payorder.order_status!=1:
                        cart_list.append(i)
                    else:
                        count-=1
                else:
                    pass
            except Exception as e:
                print(e)
        else:
            cart_list.append(i)

    return render(request,'buyer/cart.html',locals())

@LoginVaild
def user_center_site(request):
    result={'code':100000,'content':''}
    address=UserAddress.objects.all()
    user_email=request.COOKIES.get('email')
    address1 = UserAddress.objects.all()
    print('address1*********', address1)
    user_name = ''
    user_phone = ''
    user_address = ''
    for i in address1:
        # print('address.user_name', i.user_name)
        user_name = i.user_name
        user_phone = i.user_phone
        user_address = i.user_address
    if request.method=='POST':
        loginuser=LoginUserr.objects.filter(email=user_email).first()
        if loginuser:
            useraddress=UserAddress()
            useraddress.user_name=request.POST.get('user_name')
            useraddress.user_address=request.POST.get('user_address')
            useraddress.user_post=request.POST.get('user_post')
            useraddress.user_phone=request.POST.get('user_phone')
            useraddress.user_id=loginuser.id
            useraddress.save()
        else:
            result['code']=100001
            result['content']='用户不存在'
    return render(request,'buyer/user_center_site.html',locals())

def AlipayViews(request):
    payorder_id=request.GET.get('payorder_id')
    payorder=PayOrder.objects.get(id=payorder_id)
    ## 实例化支付对象
    alipay = AliPay(
        appid='2016101300674021',
        app_notify_url=None,
        app_private_key_string=alipay_private_key_string,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2",
    )
    ## 实例化订单
    order_string = alipay.api_alipay_trade_page_pay(
        subject='牛羊生鲜',  ## 交易主题
        out_trade_no=payorder.order_number,  ## 订单号
        total_amount=payorder.order_total,  ## 交易总金额
        return_url='http://127.0.0.1:8000/Buyer/payresult',  ##  请求支付，之后及时回调的一个接口
        notify_url='http://127.0.0.1:8000/Buyer/payresult'  ##  通知地址，
    )
    ##   发送支付请求
    ## 请求地址  支付网关 + 实例化订单
    result = "https://openapi.alipaydev.com/gateway.do?" + order_string
    # print(result)
    return HttpResponseRedirect(result)

def payresult(request):
    data=request.GET
    order_number=request.GET.get('out_trade_no')
    paryorder=PayOrder.objects.get(order_number=order_number)
    paryorder.order_status=1
    ## 修改订单详情的状态
    ## 查询订单详情
    order_info = paryorder.orderinfo_set.all()
    for one in order_info:
        one.status = 1
        one.save()
    paryorder.save()
    return render(request,'buyer/payresult.html',locals())


@LoginVaild
def add_cart(request):
    result={'code':100000,'content':''}
    if request.method=='POST':
        goods_id=request.POST.get('goods_id')
        count=int(request.POST.get('count',1))
        user_id=request.COOKIES.get('userid')
        goods=Goods.objects.get(id=goods_id)
        cart=Cart()
        cart.goods_number=count
        cart.goods_price=goods.goods_price
        cart.goods_total=goods.goods_price*count
        cart.goods=goods
        cart.user=LoginUserr.objects.get(id=user_id)
        cart.save()
        result['code']=100001
        result['content']='商品添加成功'
    else:
        result['code'] = 100002
        result['content'] = '请求方式不正确'
    return JsonResponse(result)

#在(detail)详情页面直接购买商品处理方法
@LoginVaild
def place_order(request):
    #地址处理
    address = UserAddress.objects.all()
    user_name = ''
    user_phone = ''
    user_address = ''
    for i in address:
        user_name = i.user_name
        user_phone = i.user_phone
        user_address = i.user_address
    ## 保存订单
    goods_id = request.GET.get('goods_id')  # 商品id
    # print('goods_id*****',goods_id)
    goods_count = request.GET.get('goods_count')  ## 订单数量
    # print('goods_count***',goods_count)
    user_id = request.COOKIES.get("userid")
    if goods_id and goods_count:
        goods_id = int(goods_id)
        goods_count = int(goods_count)
        goods = Goods.objects.get(id=goods_id)
        # print(goods.goods_price)
        ## 保存订单表
        payorder = PayOrder()
        order_number = str(time.time()).replace('.', '')  ## 生产订单编号
        payorder.order_number = order_number  ## 订单编号
        payorder.order_status = 0
        payorder.order_total = goods.goods_price * goods_count
        # print(payorder.order_total)

Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
    {% block style %}{% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
                    {% if request.COOKIES.email %}
                    <a href="#">欢迎:{{ request.COOKIES.email }}</a>
					<span>|</span>
					<a href="/Buyer/logout/">退出</a>
                    {% else %}
					<a href="/Buyer/loginn/">登录</a>
					<span>|</span>
					<a href="/Buyer/registerr/">注册</a>
				    {% endif %}
                </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/Buyer/user_center_info">用户中心</a>
					<span>|</span>
					<a href="/Buyer/cart">我的购物车</a>
					<span>|</span>
					<a href="/Buyer/user_center_order">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/Buyer/indexx/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品" id="keywords">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="getgoods()">
		</div>
		<div class="guest_cart fr">
			<a href="/Buyer/cart" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>


        {% block content %}

        {% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block script %}{% endblock %}
	<script type="text/javascript" src="/static/buyer/js/slideshow.js"></script>
    <script>
        function getgoods () {
            keywords=$('#keywords').val();
            //console.log(keywords);
            if (keywords){
                url='/Buyer/goods_list/?keywords='+keywords+'&req_type=search';
                //console.log(url)
                window.location.href=url;
            }
        }
    </script>
    <script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
</body>
</html>

Buyer/templates/buyer/cart.html
{% extends 'buyer/base.html' %}
{% block title %}
    购物车
{% endblock %}
{% block content %}
    	<div class="total_count">全部商品<em id="item">{{ count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/Buyer/place_order_more/">
    {%for cart_one in cart_list %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input class="goods_check" type="checkbox" name="goods_{{ cart_one.goods.id }}_{{ cart_one.id }}_{{ cart_one.goods_number }}" ></li>
		<li class="col02"><img src="/static/{{ cart_one.goods.picture }}"></li>
		<li class="col03">{{ cart_one.goods.goods_name }}<br><em>{{ cart_one.goods_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ cart_one.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ cart_one.goods_number }}" name="count_{{ cart_one.goods.id }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ cart_one.goods_total }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

    {% endfor %}


	<ul class="settlements">
		<li class="col01"><input id="boxall" type="checkbox" name="" ></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="item1">0.0</em><br>共计<b id="item2">0</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算" style="width: 100px;height: 50px;background-color: red"></li>
	</ul>
    </form>
{% endblock %}


{% block script %}
    <script>
        $('#boxall').click(
            function () {
                if(this.checked){
                    $('.goods_check').prop('checked',true)
                }else {
                    $('.goods_check').prop('checked',false)
                }
                add();
            }
        );
    $('.goods_check').each(
        function () {
            $(this).click(
                function () {
                    if (!this.checked){
                        $('#boxall').prop('checked',false)
                    }
                    add();
                }
            )
        }
    );
    function add () {
        var dic={num:0,total:0};
        $('.goods_check').each(
            function () {
                if(this.checked){
                    var num =parseInt($(this).parents('.cart_list_td').find('.num_show').val());
{#                    console.log(num)#}
                    var total=parseFloat($(this).parents('.cart_list_td').find('.col07').text());
{#                    console.log(total)#}
                    dic.num+=num;
                    dic.total+=total;
                    {#alert(dic.num)#}
                    {#console.log(dic.num)#}
{#                    console.log(dic.total)#}

                }

            }

        )

        $('#item1').text(dic.total);
        $('#item2').text(dic.num);
{#        console.log(dic)#}
    }
    </script>
{% endblock %}

Buyer/templates/buyer/detail.html
{% extends 'buyer/base.html' %}

{% block title %}
    商品详情
{% endblock %}

{% block content %}
    	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/static/{{ goods.picture }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<p>{{ goods.goods_xiangqing }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="price">{{ goods.goods_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl" >数 量：</div>
				<div class="num_add fl">
					<input  id="number" type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr" id="add">+</a>
					<a href="javascript:;" class="minus fr" id="sub">-</a>
				</div>
			</div>
			<div class="total">总价：<em id="total">{{ goods.goods_price }}</em>元</div>
			<div class="operate_btn">
				<a id="buynow" href="javascript:;" class="buy_btn">立即购买</a>
				<a id={{ goods.id }} href="javascript:;" class="add_cart" onclick="add_cart(this)">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="/static/buyer/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="/static/buyer/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}


{% block script %}
    <script>
        $('#add').click(
            function () {
                var price=parseFloat($('#price').text());
                var number=parseInt($('#number').val());
                number=number+1;
                $('#number').val(number);
                total=price*number;
                $('#total').text(total);
            }
        );
    $('#sub').click(
            function () {
                var price=parseFloat($('#price').text());
                var number=parseInt($('#number').val());
                number-=1;
                if (number<=1){
                    number=1;
                }
                $('#number').val(number);
                total=price*number;
                $('#total').text(total);
            }
        );
    $('#buynow').click(
        function () {
            url='/Buyer/place_order/?goods_id='+{{ goods.id }}+"&goods_count="+$('#number').val();
            console.log(url);
            window.location.href=url;
        }
    );

            function add_cart(req) {
            var goods_id=req.id;
            var count=$('#number').val();
            console.log(goods_id);
            url="/Buyer/add_cart/";
            send_data={
                "goods_id":goods_id,
                'count':count,
                "csrfmiddlewaretoken":'{{ csrf_token }}'
            };
            $.ajax(
                {
                    url:url,
                    type:'post',
                    data:send_data,
                    success:function (data) {
                        console.log(data);
                        alert('添加成功')
                    },
                    error:function (err) {
                        console.log(err)
                    }
                }
            )
        }
    </script>
{% endblock %}

Buyer/templates/buyer/payresult.html
{% extends 'buyer/base.html' %}

{% block title %}
    支付结果
{% endblock %}

{% block content %}
    <h1 style="font-size: 20px;text-align: center;color: red">
    支付成功
    </h1>

{#    {% for i in data %}#}
{#    {{ i }}#}
{#    {% endfor %}#}
{% endblock %}

Buyer/templates/buyer/user_center_order.html
{% extends 'buyer/base.html' %}

{% block title %}
    订单
{% endblock %}
{% block content%}
    	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/Buyer/user_center_info">· 个人信息</a></li>
				<li><a href="/Buyer/user_center_order" class="active">· 全部订单</a></li>
				<li><a href="/Buyer/user_center_site">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for i in payorder %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ i.order_date }}</li>
					<li class="col02">订单号：{{ i.order_number }}</li>
					<li class="col02 stress">{{ i.get_order_status_display}}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_info in i.orderinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ order_info.goods.picture }}"></li>
									<li class="col02">{{ order_info.goods.goods_name }}<em>{{ order_info.goods_price }}元/500g</em></li>
									<li class="col03">{{ order_info.goods_count }}</li>
									<li class="col04">{{ order_info.goods_total_price }}元</li>
								</ul>
							{% endfor %}
                            </td>
							<td width="15%">{{ i.order_total }}元</td>
							<td width="15%">{{ i.get_order_status_display}}</td>
                                {% if i.order_status == 0 %}
							<td width="15%"><a href="/Buyer/AlipayViews/?payorder_id={{ i.id }}" class="oper_btn">去付款</a></td>
                                {% else %}
                            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						        {% endif %}
                        </tr>

					</tbody>
				</table>
            {% endfor %}
				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页</a>
				</div>
		</div>
	</div>
{% endblock %}